### ISSUE TITLE
Running only on certain files

### ISSUE THREAD

**Issue by plievone** [markis/strip-whitespace-plugin#4]
Hi! This looks very promising! How would you run this only on specific files, such as `*.templates.ts`?

Could you also add a license to repo?

**Comment by markis** [comment]
I hadn't considered the specific file or file globs scenario.  But I could see benefits for adding it.  Let me investigate.

**Comment by markis** [comment]
I am just curious, is inclusion or exclusion of files more important?  Would you rather this plugin have options to only include specific files or would you rather have the opposite, an option to exclude specific files?

**Comment by plievone** [comment]
Thanks for considering this! For me I would guess inclusion would be more important. I haven't looked much into webpack plugin internals, but could it use some regex like loaders use?

**Comment by markis** [comment]
I am also not entirely sure, how it will work either. I just took the plunge into the webpack plugin internals this week. So, I will dig further and see what is feasible.

**Comment by markis** [comment]
It looks like it would be more feasible to just turn this into a loader instead.  Let me know how it works for you.

https://npm.im/strip-whitespace-loader

**Comment by plievone** [comment]
Yes, it seems more sensible as a loader. In fact, the actual loader is so minimal that I might use  `strip-whitespace` directly, so that I can modify the loader at will (such as stripping also html-comments inside strings from special files).

**Comment by markis** [comment]
That is a great idea!  Maybe it should be an option for strip-whitespace?  Would you mind filling a pull request?
